#!/usr/bin/env python3

import sys
import subprocess

timeout = sys.argv[1]
pargs = sys.argv[2:]

try:
    subprocess.run(pargs, stdin=sys.stdin, stdout=sys.stdout, stderr=sys.stderr, timeout=int(timeout))
except subprocess.TimeoutExpired:
    sys.exit(1)
